[build]
builder = "nixpacks"
buildCommand = "npm install && npm run client:build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
MONGO_URI = "mongodb+srv://nomnk5138:Redzone12@spinev0.zbqy7hv.mongodb.net/spineline?retryWrites=true&w=majority"
JWT_SECRET = "spineline-jwt-secret-2024"
ADMIN_EMAIL = "admin@spineline.com"
ADMIN_PASSWORD = "SpineLine2024!"
ADMIN_USERNAME = "spineline_admin"
