services:
  # Backend API Service
  - type: web
    name: spineline-api
    env: node
    plan: starter
    buildCommand: cd server && npm ci --only=production
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromDatabase:
          name: spineline-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        value: admin@spineline.com
      - key: ADMIN_PASSWORD
        value: SpineLine2024!
    autoDeploy: true

  # Frontend Static Site
  - type: static
    name: spineline-frontend
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /api/*
        destination: https://spineline-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://spineline-api.onrender.com
    autoDeploy: true

databases:
  - name: spineline-mongodb
    databaseName: spineline
    user: spineline_user
    plan: starter
